apiVersion: v1
kind: PersistentVolume
metadata:
  name: statefulset-ex-1
  labels:
    type: local
spec:
  storageClassName: example
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/vol1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: statefulset-ex-2
  labels:
    type: local
spec:
  storageClassName: example
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/vol2"